
import { BuildingType, ResourceType } from './enums.js';

const PER_10_MINUTES = 600;
const rate = (amount) => amount / PER_10_MINUTES;

const QUANTITY_MULT = 1.015;
const LEVEL_MULT = 1.50; 

export const BUILDING_DEFS = {
  [BuildingType.HOUSE]: {
    id: BuildingType.HOUSE,
    buildMode: 'QUANTITY',
    baseCost: { money: 1000, oil: 0, ammo: 0 },
    costMultiplier: QUANTITY_MULT,
    productionRate: { [ResourceType.MONEY]: rate(500) },
    maxLevel: 200000,
    buildTime: 30000,
    score: 1,
  },
  [BuildingType.FACTORY]: {
    id: BuildingType.FACTORY,
    buildMode: 'QUANTITY',
    baseCost: { money: 20000, oil: 1000, ammo: 0 },
    costMultiplier: QUANTITY_MULT,
    productionRate: { [ResourceType.MONEY]: rate(2500) },
    maxLevel: 200000,
    buildTime: 30000,
    score: 5,
  },
  [BuildingType.SKYSCRAPER]: {
    id: BuildingType.SKYSCRAPER,
    buildMode: 'QUANTITY',
    baseCost: { money: 100000, oil: 50000, ammo: 0 },
    costMultiplier: QUANTITY_MULT,
    productionRate: { [ResourceType.MONEY]: rate(12500) },
    maxLevel: 200000,
    buildTime: 30000,
    score: 100,
  },
  [BuildingType.BANK]: {
    id: BuildingType.BANK,
    buildMode: 'LEVEL',
    baseCost: { money: 500000, oil: 0, ammo: 0 }, 
    costMultiplier: 1.0, 
    costScaling: 'EXPONENTIAL', 
    productionRate: {},
    maxLevel: 15, 
    buildTime: 30000,
    score: 50,
  },
  [BuildingType.MARKET]: {
    id: BuildingType.MARKET,
    buildMode: 'LEVEL',
    baseCost: { money: 25000, oil: 0, ammo: 0 },
    costMultiplier: LEVEL_MULT,
    productionRate: {},
    maxLevel: 5,
    buildTime: 10000,
    score: 15,
  },
  [BuildingType.DIAMOND_MINE]: {
    id: BuildingType.DIAMOND_MINE,
    buildMode: 'LEVEL',
    baseCost: { money: 10000000, oil: 0, ammo: 0 },
    costMultiplier: 5.0, 
    costScaling: 'EXPONENTIAL',
    productionRate: { [ResourceType.DIAMOND]: rate(1/6) }, 
    maxLevel: 5,
    buildTime: 300000,
    score: 500,
  },
  [BuildingType.OIL_RIG]: {
    id: BuildingType.OIL_RIG,
    buildMode: 'QUANTITY',
    baseCost: { money: 8000, oil: 0, ammo: 2000 },
    costMultiplier: QUANTITY_MULT,
    productionRate: { [ResourceType.OIL]: rate(200) },
    maxLevel: 200000,
    buildTime: 30000,
    score: 3,
  },
  [BuildingType.GOLD_MINE]: {
    id: BuildingType.GOLD_MINE,
    buildMode: 'QUANTITY',
    baseCost: { money: 15000, oil: 500, ammo: 1500 },
    costMultiplier: QUANTITY_MULT,
    productionRate: { [ResourceType.GOLD]: rate(64) },
    maxLevel: 200000,
    buildTime: 30000,
    score: 25,
  },
  [BuildingType.MUNITIONS_FACTORY]: {
    id: BuildingType.MUNITIONS_FACTORY,
    buildMode: 'QUANTITY',
    baseCost: { money: 5000, oil: 500, ammo: 0 },
    costMultiplier: QUANTITY_MULT,
    productionRate: { [ResourceType.AMMO]: rate(700) },
    maxLevel: 200000,
    buildTime: 30000,
    score: 4,
  },
  [BuildingType.UNIVERSITY]: {
    id: BuildingType.UNIVERSITY,
    buildMode: 'LEVEL',
    baseCost: { money: 50000, oil: 5000, ammo: 0 },
    costMultiplier: 2.05, 
    productionRate: {},
    maxLevel: 15, 
    buildTime: 30000, 
    score: 40,
  },
  [BuildingType.BARRACKS]: {
    id: BuildingType.BARRACKS,
    buildMode: 'LEVEL',
    baseCost: { money: 50000, oil: 0, ammo: 1000 },
    costMultiplier: 2.25,
    productionRate: {},
    maxLevel: 20,
    buildTime: 15000, 
    score: 10,
  },
  [BuildingType.TANK_FACTORY]: {
    id: BuildingType.TANK_FACTORY,
    buildMode: 'LEVEL',
    baseCost: { money: 500000, oil: 25000, ammo: 10000 },
    costMultiplier: 1.9,
    productionRate: {},
    maxLevel: 15,
    buildTime: 60000,
    score: 35,
  },
  [BuildingType.SHIPYARD]: {
    id: BuildingType.SHIPYARD,
    buildMode: 'LEVEL',
    baseCost: { money: 1000000, oil: 50000, ammo: 20000 },
    costMultiplier: 1.75,
    productionRate: {},
    maxLevel: 10,
    buildTime: 90000,
    score: 35,
  },
  [BuildingType.AIRFIELD]: {
    id: BuildingType.AIRFIELD,
    buildMode: 'LEVEL',
    baseCost: { money: 1500000, oil: 100000, ammo: 50000 },
    costMultiplier: 1.70,
    productionRate: {},
    maxLevel: 10,
    buildTime: 120000,
    score: 35,
  },
};
