// ============================================================
// ENUMS - Mirror of types/enums.ts (no TypeScript)
// ============================================================

export const ResourceType = {
  MONEY: 'MONEY',
  OIL: 'OIL',
  AMMO: 'AMMO',
  GOLD: 'GOLD',
  DIAMOND: 'DIAMOND',
};

export const BuildingType = {
  HOUSE: 'HOUSE',
  FACTORY: 'FACTORY',
  SKYSCRAPER: 'SKYSCRAPER',
  BANK: 'BANK',
  MARKET: 'MARKET',
  DIAMOND_MINE: 'DIAMOND_MINE',
  OIL_RIG: 'OIL_RIG',
  GOLD_MINE: 'GOLD_MINE',
  MUNITIONS_FACTORY: 'MUNITIONS_FACTORY',
  UNIVERSITY: 'UNIVERSITY',
  BARRACKS: 'BARRACKS',
  TANK_FACTORY: 'TANK_FACTORY',
  SHIPYARD: 'SHIPYARD',
  AIRFIELD: 'AIRFIELD',
};

export const UnitType = {
  CYBER_MARINE: 'CYBER_MARINE',
  HEAVY_COMMANDO: 'HEAVY_COMMANDO',
  SCOUT_TANK: 'SCOUT_TANK',
  TITAN_MBT: 'TITAN_MBT',
  WRAITH_GUNSHIP: 'WRAITH_GUNSHIP',
  ACE_FIGHTER: 'ACE_FIGHTER',
  AEGIS_DESTROYER: 'AEGIS_DESTROYER',
  PHANTOM_SUB: 'PHANTOM_SUB',
  SALVAGER_DRONE: 'SALVAGER_DRONE',
};

export const TechType = {
  DEEP_DRILLING: 'DEEP_DRILLING',
  GOLD_REFINING: 'GOLD_REFINING',
  MASS_PRODUCTION: 'MASS_PRODUCTION',
  STRATEGIC_COMMAND: 'STRATEGIC_COMMAND',
  BASIC_TRAINING: 'BASIC_TRAINING',
  PATROL_TRAINING: 'PATROL_TRAINING',
  BALLISTICS: 'BALLISTICS',
  EXPLOSIVE_CHEMISTRY: 'EXPLOSIVE_CHEMISTRY',
  COMBUSTION_ENGINE: 'COMBUSTION_ENGINE',
  HEAVY_PLATING: 'HEAVY_PLATING',
  NAVAL_ENGINEERING: 'NAVAL_ENGINEERING',
  SONAR_TECH: 'SONAR_TECH',
  STEALTH_HULL: 'STEALTH_HULL',
  AERODYNAMICS: 'AERODYNAMICS',
  JET_ENGINES: 'JET_ENGINES',
  PRECISION_BOMBING: 'PRECISION_BOMBING',
  DRONE_BATTLE_TECH: 'DRONE_BATTLE_TECH',
  UNLOCK_CYBER_MARINE: 'UNLOCK_CYBER_MARINE',
  UNLOCK_HEAVY_COMMANDO: 'UNLOCK_HEAVY_COMMANDO',
  UNLOCK_SCOUT_TANK: 'UNLOCK_SCOUT_TANK',
  UNLOCK_TITAN_MBT: 'UNLOCK_TITAN_MBT',
  UNLOCK_WRAITH_GUNSHIP: 'UNLOCK_WRAITH_GUNSHIP',
  UNLOCK_ACE_FIGHTER: 'UNLOCK_ACE_FIGHTER',
  UNLOCK_AEGIS_DESTROYER: 'UNLOCK_AEGIS_DESTROYER',
  UNLOCK_PHANTOM_SUB: 'UNLOCK_PHANTOM_SUB',
  UNLOCK_SALVAGER_DRONE: 'UNLOCK_SALVAGER_DRONE',
};

export const BotPersonality = {
  WARLORD: 'WARLORD',
  TURTLE: 'TURTLE',
  TYCOON: 'TYCOON',
  ROGUE: 'ROGUE',
};

export const UnitCategory = {
  GROUND: 'GROUND',
  ARTILLERY: 'ARTILLERY',
  TANK: 'TANK',
  NAVAL: 'NAVAL',
  AIR: 'AIR',
};

export const TechCategory = {
  PRODUCTIVE: 'PRODUCTIVE',
  LOGISTICS: 'LOGISTICS',
  MILITARY_GROUND: 'MILITARY_GROUND',
  MILITARY_MECH: 'MILITARY_MECH',
  MILITARY_AIR: 'MILITARY_AIR',
  MILITARY_NAVAL: 'MILITARY_NAVAL',
};
