
import { BuildingType, TechCategory, TechType } from './enums.js';

const MINUTE = 60 * 1000;
const HOUR = 60 * MINUTE;

export const TECH_DEFS = {
  [TechType.DEEP_DRILLING]: {
    id: TechType.DEEP_DRILLING,
    category: TechCategory.PRODUCTIVE,
    reqUniversityLevel: 2,
    reqBuildings: { [BuildingType.OIL_RIG]: 5 },
    cost: { money: 10000000, ammo: 500000, oil: 100000, gold: 250000 },
    costMultiplier: 3.0,
    maxLevel: 20,
    researchTime: 15 * MINUTE,
    score: 150,
  },
  [TechType.MASS_PRODUCTION]: {
    id: TechType.MASS_PRODUCTION,
    category: TechCategory.PRODUCTIVE,
    reqUniversityLevel: 3,
    reqBuildings: { [BuildingType.FACTORY]: 3 },
    cost: { money: 10000000, ammo: 500000, oil: 100000, gold: 250000 },
    costMultiplier: 3.0,
    maxLevel: 20,
    researchTime: 20 * MINUTE,
    score: 200,
  },
  [TechType.GOLD_REFINING]: {
    id: TechType.GOLD_REFINING,
    category: TechCategory.PRODUCTIVE,
    reqUniversityLevel: 5,
    reqBuildings: { [BuildingType.GOLD_MINE]: 2 },
    cost: { money: 10000000, ammo: 500000, oil: 100000, gold: 250000 },
    costMultiplier: 3.0,
    maxLevel: 20,
    researchTime: 45 * MINUTE,
    score: 500,
  },
  [TechType.STRATEGIC_COMMAND]: {
    id: TechType.STRATEGIC_COMMAND,
    category: TechCategory.LOGISTICS,
    reqUniversityLevel: 3,
    reqEmpirePoints: 5000,
    cost: { money: 50000000, oil: 5000000, ammo: 2500000 },
    costMultiplier: 10.0,
    maxLevel: 3,
    researchTime: 12 * HOUR,
    score: 10000,
  },
  [TechType.UNLOCK_SALVAGER_DRONE]: {
    id: TechType.UNLOCK_SALVAGER_DRONE,
    category: TechCategory.LOGISTICS,
    reqUniversityLevel: 3,
    reqTechs: [TechType.PATROL_TRAINING],
    cost: { money: 200000, oil: 1000, ammo: 500 },
    researchTime: 5 * MINUTE,
    score: 25,
  },
  [TechType.DRONE_BATTLE_TECH]: {
    id: TechType.DRONE_BATTLE_TECH,
    category: TechCategory.LOGISTICS,
    reqUniversityLevel: 5,
    reqTechs: [TechType.UNLOCK_SALVAGER_DRONE],
    cost: { money: 1000000, oil: 50000, ammo: 25000 },
    costMultiplier: 2.0,
    maxLevel: 10,
    researchTime: 30 * MINUTE,
    score: 500,
  },
  [TechType.BASIC_TRAINING]: {
    id: TechType.BASIC_TRAINING,
    category: TechCategory.MILITARY_GROUND,
    reqUniversityLevel: 1,
    cost: { money: 15000, oil: 0, ammo: 500 },
    researchTime: 2 * MINUTE,
    score: 10,
  },
  [TechType.UNLOCK_CYBER_MARINE]: {
    id: TechType.UNLOCK_CYBER_MARINE,
    category: TechCategory.MILITARY_GROUND,
    reqUniversityLevel: 1,
    reqBuildings: { [BuildingType.BARRACKS]: 1 },
    cost: { money: 25000, oil: 0, ammo: 1000 },
    researchTime: 5 * MINUTE,
    score: 50,
  },
  [TechType.UNLOCK_HEAVY_COMMANDO]: {
    id: TechType.UNLOCK_HEAVY_COMMANDO,
    category: TechCategory.MILITARY_GROUND,
    reqUniversityLevel: 3,
    reqBuildings: { [BuildingType.BARRACKS]: 5 },
    reqTechs: [TechType.UNLOCK_CYBER_MARINE, TechType.BASIC_TRAINING],
    cost: { money: 250000, oil: 0, ammo: 50000 },
    researchTime: 15 * MINUTE,
    score: 150,
  },
  [TechType.PATROL_TRAINING]: {
    id: TechType.PATROL_TRAINING,
    category: TechCategory.MILITARY_GROUND,
    reqUniversityLevel: 5,
    reqBuildings: { [BuildingType.BARRACKS]: 1 },
    cost: { money: 5000000, oil: 50000, ammo: 50000 },
    researchTime: 2 * HOUR,
    score: 500,
    maxLevel: 10,
    costMultiplier: 2.0 
  },
  [TechType.COMBUSTION_ENGINE]: {
    id: TechType.COMBUSTION_ENGINE,
    category: TechCategory.MILITARY_MECH,
    reqUniversityLevel: 2,
    reqBuildings: { [BuildingType.OIL_RIG]: 3 },
    cost: { money: 300000, oil: 25000, ammo: 0 }, 
    researchTime: 20 * MINUTE,
    score: 100,
  },
  [TechType.BALLISTICS]: {
    id: TechType.BALLISTICS,
    category: TechCategory.MILITARY_MECH,
    reqUniversityLevel: 2,
    cost: { money: 150000, oil: 5000, ammo: 10000 },
    researchTime: 15 * MINUTE,
    score: 80,
  },
  [TechType.EXPLOSIVE_CHEMISTRY]: {
    id: TechType.EXPLOSIVE_CHEMISTRY,
    category: TechCategory.MILITARY_MECH,
    reqUniversityLevel: 4,
    reqBuildings: { [BuildingType.MUNITIONS_FACTORY]: 5 },
    reqTechs: [TechType.BALLISTICS],
    cost: { money: 2500000, oil: 50000, ammo: 100000 },
    researchTime: 2 * HOUR,
    score: 500,
  },
  [TechType.UNLOCK_SCOUT_TANK]: {
    id: TechType.UNLOCK_SCOUT_TANK,
    category: TechCategory.MILITARY_MECH,
    reqUniversityLevel: 4,
    reqBuildings: { [BuildingType.TANK_FACTORY]: 2 },
    reqTechs: [TechType.COMBUSTION_ENGINE, TechType.BALLISTICS],
    cost: { money: 500000, oil: 25000, ammo: 10000 },
    researchTime: 30 * MINUTE,
    score: 300,
  },
  [TechType.HEAVY_PLATING]: {
    id: TechType.HEAVY_PLATING,
    category: TechCategory.MILITARY_MECH,
    reqUniversityLevel: 5,
    reqBuildings: { [BuildingType.FACTORY]: 10 },
    cost: { money: 5000000, oil: 200000, ammo: 0 },
    researchTime: 2 * HOUR,
    score: 600,
  },
  [TechType.UNLOCK_TITAN_MBT]: {
    id: TechType.UNLOCK_TITAN_MBT,
    category: TechCategory.MILITARY_MECH,
    reqUniversityLevel: 6,
    reqBuildings: { [BuildingType.TANK_FACTORY]: 5 },
    reqTechs: [TechType.HEAVY_PLATING, TechType.UNLOCK_SCOUT_TANK, TechType.EXPLOSIVE_CHEMISTRY],
    cost: { money: 2000000, oil: 100000, ammo: 50000 },
    researchTime: 1 * HOUR,
    score: 600,
  },
  [TechType.AERODYNAMICS]: {
    id: TechType.AERODYNAMICS,
    category: TechCategory.MILITARY_AIR,
    reqUniversityLevel: 5,
    cost: { money: 3000000, oil: 500000, ammo: 0 },
    researchTime: 3 * HOUR,
    score: 800,
  },
  [TechType.UNLOCK_WRAITH_GUNSHIP]: {
    id: TechType.UNLOCK_WRAITH_GUNSHIP,
    category: TechCategory.MILITARY_AIR,
    reqUniversityLevel: 6,
    reqBuildings: { [BuildingType.AIRFIELD]: 2 },
    reqTechs: [TechType.AERODYNAMICS, TechType.JET_ENGINES],
    cost: { money: 3000000, oil: 100000, ammo: 50000 },
    researchTime: 90 * MINUTE,
    score: 800,
  },
  [TechType.JET_ENGINES]: {
    id: TechType.JET_ENGINES,
    category: TechCategory.MILITARY_AIR,
    reqUniversityLevel: 7,
    reqTechs: [TechType.AERODYNAMICS],
    cost: { money: 15000000, oil: 2000000, ammo: 0 },
    researchTime: 6 * HOUR,
    score: 2500,
  },
  [TechType.UNLOCK_ACE_FIGHTER]: {
    id: TechType.UNLOCK_ACE_FIGHTER,
    category: TechCategory.MILITARY_AIR,
    reqUniversityLevel: 8,
    reqBuildings: { [BuildingType.AIRFIELD]: 5 },
    reqTechs: [TechType.UNLOCK_WRAITH_GUNSHIP, TechType.PRECISION_BOMBING],
    cost: { money: 100000000, oil: 500000, ammo: 200000 },
    researchTime: 3 * HOUR,
    score: 1500,
  },
  [TechType.PRECISION_BOMBING]: {
    id: TechType.PRECISION_BOMBING,
    category: TechCategory.MILITARY_AIR,
    reqUniversityLevel: 9,
    reqTechs: [TechType.AERODYNAMICS, TechType.BALLISTICS],
    cost: { money: 50000000, oil: 1000000, ammo: 2000000 },
    researchTime: 10 * HOUR,
    score: 5000,
  },
  [TechType.NAVAL_ENGINEERING]: {
    id: TechType.NAVAL_ENGINEERING,
    category: TechCategory.MILITARY_NAVAL,
    reqUniversityLevel: 10,
    reqBuildings: { [BuildingType.SHIPYARD]: 7 },
    reqEmpirePoints: 25000,
    cost: { money: 50000000, oil: 1000000, ammo: 2000000, gold: 250000 },
    researchTime: 4 * HOUR,
    score: 5000,
  },
  [TechType.SONAR_TECH]: {
    id: TechType.SONAR_TECH,
    category: TechCategory.MILITARY_NAVAL,
    reqUniversityLevel: 10,
    reqBuildings: { [BuildingType.SHIPYARD]: 12 },
    reqTechs: [TechType.NAVAL_ENGINEERING],
    reqEmpirePoints: 50000,
    cost: { money: 100000000, oil: 1500000, ammo: 10000000, gold: 450000 },
    researchTime: 6 * HOUR,
    score: 10000,
  },
  [TechType.UNLOCK_AEGIS_DESTROYER]: {
    id: TechType.UNLOCK_AEGIS_DESTROYER,
    category: TechCategory.MILITARY_NAVAL,
    reqUniversityLevel: 10,
    reqBuildings: { [BuildingType.SHIPYARD]: 10 },
    reqTechs: [TechType.NAVAL_ENGINEERING, TechType.SONAR_TECH],
    reqEmpirePoints: 65000,
    cost: { money: 200000000, oil: 1500000, ammo: 7500000, gold: 2500000 },
    researchTime: 8 * HOUR,
    score: 15000,
  },
  [TechType.STEALTH_HULL]: {
    id: TechType.STEALTH_HULL,
    category: TechCategory.MILITARY_NAVAL,
    reqUniversityLevel: 14,
    reqBuildings: { [BuildingType.SHIPYARD]: 10 },
    reqTechs: [TechType.NAVAL_ENGINEERING, TechType.SONAR_TECH],
    reqEmpirePoints: 80000,
    cost: { money: 105000000, oil: 2500000, ammo: 10000000, gold: 700000 },
    researchTime: 12 * HOUR,
    score: 25000,
  },
  [TechType.UNLOCK_PHANTOM_SUB]: {
    id: TechType.UNLOCK_PHANTOM_SUB,
    category: TechCategory.MILITARY_NAVAL,
    reqUniversityLevel: 14,
    reqBuildings: { [BuildingType.SHIPYARD]: 12 },
    reqTechs: [TechType.STEALTH_HULL, TechType.UNLOCK_AEGIS_DESTROYER],
    reqEmpirePoints: 100000,
    cost: { money: 600000000, oil: 4000000, ammo: 15000000, gold: 1000000, diamond: 50 },
    researchTime: 24 * HOUR,
    score: 50000,
  },
};
