
import { BuildingType, ResourceType, TechCategory, TechType, UnitCategory, UnitType } from './enums';
import type { GameState } from './state';

export interface Cost {
  money: number;
  oil: number;
  ammo: number;
  diamond?: number;
}

export interface BuildingDef {
  id: BuildingType;
  baseCost: Cost;
  costMultiplier: number;
  costScaling?: 'EXPONENTIAL' | 'LINEAR'; 
  productionRate: Partial<Record<ResourceType, number>>; 
  storageIncrease?: Partial<Record<ResourceType, number>>; 
  maxLevel: number; 
  buildTime: number; 
  imagePlaceholder: string;
  translationKey: string; 
  buildMode: 'QUANTITY' | 'LEVEL'; 
  score: number; 
}

export interface UnitDef {
  id: UnitType;
  category: UnitCategory;
  hp: number; 
  attack: number;
  defense: number;
  threshold: number;
  cost: Cost;
  recruitTime: number; 
  upkeep: Partial<Record<ResourceType, number>>; 
  translationKey: string; 
  rapidFire: Partial<Record<UnitType, number>>;
  reqTech: TechType;
  score: number; 
}

export interface TechDef {
  id: TechType;
  category: TechCategory;
  cost: Cost;
  translationKey: string;
  researchTime: number; 
  reqUniversityLevel: number;
  reqBuildings?: Partial<Record<BuildingType, number>>; 
  reqTechs?: TechType[]; 
  reqEmpirePoints?: number; // NEW: Stat requirement for advanced techs
  score: number;
  maxLevel?: number; 
  costMultiplier?: number; 
}

export interface CampaignLevel {
  id: number;
  nameKey: string;
  descriptionKey: string;
  enemyArmy: Partial<Record<UnitType, number>>;
  reward: Partial<Record<ResourceType, number>>;
  difficulty: 'EASY' | 'MEDIUM' | 'HARD' | 'EXTREME' | 'NIGHTMARE';
}

export interface MarketEvent {
  id: string;
  nameKey: string;
  descriptionKey: string;
  priceModifiers: Partial<Record<ResourceType, number>>; 
  duration: number; 
}

export interface MarketOffer {
  id: string;
  type: 'BUY' | 'SELL'; 
  resource: ResourceType;
  pricePerUnit: number;
  totalAmount: number;
  amountSold: number;
}

export interface TutorialStep {
    id: string;
    titleKey: string;
    descKey: string;
    reward: Partial<Record<ResourceType, number>>;
    buildingReward?: Partial<Record<BuildingType, number>>; // New: Reward buildings directly
    unitReward?: Partial<Record<UnitType, number>>; // New: Reward units directly
    condition: (state: GameState) => boolean;
    progressCondition?: (state: GameState) => boolean | number; 
    targetTab: string; 
    targetElementId?: string; 
}

export type Language = 'en' | 'es';

export interface TranslationDictionary {
  common: {
    resources: Record<string, string>;
    tiers: {
        soft: string;
        light: string;
        armored: string;
        heavy: string;
    };
    stats: {
      empire_points: string;
      hp: string;
      attack: string;
      defense: string;
      upkeep: string;
      cost: string;
      research_time: string;
      recruit_cap: string;
      sustain_cap: string;
      arm_short: string; // ARM / UMB
      pen_short: string; // PEN
      min_dmg: string;
      unit_class: string;
    };
    actions: {
      construct: string;
      upgrade: string;
      recruit: string;
      deploy: string;
      cancel: string;
      acknowledge: string;
      research: string; 
      researching: string;
      researched: string;
      deposit: string; 
      withdraw: string; 
      simulate: string; 
      reset_sim: string; 
      attack: string;
      scout: string;
      trade: string; 
      buy: string; 
      sell: string; 
      claim_reward: string; 
      delete: string; 
      archive: string; 
      select_all: string;
      max: string; 
      accept_mission: string; 
      click_here: string;
      previous: string;
      next: string;
      locate: string;
      speed_up: string;
      rapid_deployment: string;
      spy: string;
      inspect: string;
      menu: string;
      locked_war: string;
      limit_reached: string;
      launch_raid: string;
      launch_war: string;
      close: string;
      decrypt: string;
      repair: string;
    };
    ui: {
      loading: string;
      advisor_title: string;
      logs_title: string;
      reset: string;
      reset_confirm: string;
      settings: string;
      language: string;
      fullscreen: string;
      fs_on: string;
      fs_off: string;
      quantity: string;
      production_rate: string;
      rate: string;
      units: string;
      you: string;
      max_storage: string;
      next_cost: string;
      req_university: string; 
      nav_research: string; 
      nav_economy: string; 
      nav_reports: string; 
      nav_simulator: string; 
      nav_campaign: string;
      nav_market: string; 
      bank_balance: string; 
      income: string; 
      expenses: string; 
      net_flow: string; 
      current_rate: string; 
      next_rate_update: string; 
      bank_yield: string; 
      strong_vs: string;
      weak_vs: string;
      research_busy: string;
      time_remaining: string;
      level: string;
      type_label: string;
      constructible: string;
      upgradeable: string;
      output_label: string;
      cost_label: string;
      available_label: string;
      prereq_label: string;
      efficiency_label: string;
      combat_efficiency: string;
      storage: string;
      inventory: string; 
      status: string; 
      storage_full: string;
      commander_profile: string;
      total_score: string;
      tech_acquired: string;
      req_not_met: string;
      req_met: string;
      req_missing: string;
      req_tech: string; 
      req_short: string; 
      unknown_tech: string; 
      status_locked: string;
      status_unlocked: string;
      status_damaged: string;
      status_repaired: string;
      status_busy: string;
      out_range: string;
      in_range: string;
      power_ratio_label: string;
      commander_intel: string;
      strategic_profile: string;
      technical_specs: string;
      target_outside_range: string;
      instant_arrival_desc: string;
      total_troops: string;
      select_target_zone: string;
      ready_for_deployment: string;
      tutorial: string; 
      objective: string; 
      completed: string; 
      search: string; 
      no_results: string; 
      financial_report: string; 
      hourly_projection: string; 
      no_income: string; 
      no_expenses: string;
      page: string; 
      total: string;
      active_units: string;
      training_queue: string;
      construction_queue: string;
      blue_team: string;
      red_team: string;
      draw: string;
      time_base: string;
      open_orders: string;
      completion_rewards: string;
      mission_list: string;
      select_op: string;
      sat_link: string;
      resupplying: string;
      strike_force: string;
      est_power: string;
      threat_level: string;
      threat_short: string;
      threat_desc_diamond: string;
      threat_source_diamond: string;
      threat_frozen_war: string;
      threat_passive_title: string;
      threat_high_storage: string;
      threat_base_decay: string;
      threat_net_flow: string;
      threat_active_title: string;
      threat_act_build: string;
      threat_act_research: string;
      threat_act_pvp: string;
      threat_act_camp: string;
      under_attack: string;
      attack_outbound: string;
      incoming_hostiles: string;
      active_ops: string;
      alert_incoming: string;
      log_defense_win: string;
      log_defense_loss: string;
      log_war_declared_offline: string;
      log_war_declared: string;
      log_war_overtime: string;
      log_war_ended: string;
      log_intel_revenge: string;
      log_intel_fleet: string;
      loot_estimated: string;
      loot_reroll: string;
      system_status: string;
      threat_diamond: string;
      intel_unknown: string;
      base_command: string;
      operations: string;
      intelligence: string;
      system: string;
      nav_base: string;
      nav_army: string;
      nav_map: string;
      nav_intel: string;
      app_title: string;
      app_subtitle: string;
      sys_monitor: string;
      sys_idle: string;
      barracks_idle: string;
      lab_idle: string;
      no_ops: string;
      all: string;
      performance: string;
      trend: string;
      tier_class: string;
      power_ratio: string;
      range_label: string;
      action_col: string;
      war_won: string;
      war_lost: string;
      summary: string;
      your_losses: string;
      enemies_killed: string;
      logistics_banking: string;
      liquidation: string;
      bank_transfer: string;
      defeat_salvage: string;
      console: string;
      sys_ready: string;
      cmd_history: string;
      peace_time: string;
      tactical_op: string;
      travel_time: string;
      raid_capacity_info: string;
      war_victory_secured: string;
      war_overflow: string;
      war_banked: string;
      intercept_title: string;
      impact_t_minus: string;
      aggressor: string;
      threat_score: string;
      threat_assessment: string;
      threat_extreme: string;
      threat_standard: string;
      signal_encrypted: string;
      signal_decrypted: string;
      encryption_desc: string;
      recommended_counters: string;
      hostile_signal: string;
      impact: string;
      warning: string;
      cmd_slots: string;
      active_ops_limit: string;
      no_inbound_waves: string;
      no_active_threats: string;
      mission_patrol: string;
      mission_campaign: string;
      profile_unknown: string;
      mission_type_campaign: string;
      mission_type_patrol: string;
      mission_type_tactical: string;
    };
    menu: {
      new_game: string;
      continue_game: string;
      export_save: string;
      import_save: string;
      save_exit: string;
      save_success: string;
      import_error: string;
      confirm_new: string;
      initializing: string;
      access_granted: string;
    };
    categories: Record<string, string>; 
    war: {
      title: string;
      vs: string;
      time_left: string;
      wave: string;
      next_wave: string;
      loot_pool: string;
      loot_pool_desc: string;
      declare_title: string;
      declare_desc: string;
      already_war: string;
      attacks_left: string;
      launch_counter: string;
      active_against_empire: string;
      bot_attack_time: string;
      status_war: string;
      status_protected: string;
      status_cooldown: string;
      status_ready: string;
      status_safe: string;
      status_wait: string;
      status_newbie_protection: string;
      status_peace_time: string;
      status_time_remaining: string;
      status_attacks_enabled: string;
    };
    diplomacy: {
      title: string;
      inbox: string;
      proposals: string;
      relations: string;
      treaties: string;
      actions: string;
      no_proposals: string;
      no_treaties: string;
      no_relations: string;
      send_proposal: string;
      accept: string;
      reject: string;
      counter: string;
      expires_in: string;
      from: string;
      to: string;
      pending: string;
      accepted: string;
      rejected: string;
      expired: string;
      alliance: string;
      trade_deal: string;
      non_aggression: string;
      mutual_defense: string;
      ceasefire: string;
      tribute: string;
      select_target: string;
      select_action: string;
      offer_resources: string;
      request_resources: string;
      duration: string;
      permanent: string;
      hours: string;
      your_reputation: string;
      reputation_trusted: string;
      reputation_friendly: string;
      reputation_positive: string;
      reputation_neutral: string;
      reputation_suspicious: string;
      reputation_hostile: string;
      reputation_hated: string;
    };
    intelligence: {
      title: string;
      threats: string;
      threats_desc: string;
      allies: string;
      allies_desc: string;
      events: string;
      events_desc: string;
      incoming_threats: string;
      detected: string;
      warning_time: string;
      no_threats: string;
      no_allies: string;
      no_events: string;
      attack_planned: string;
      operation_type: string;
      participants: string;
      target: string;
      war_declared: string;
      war_ended: string;
      alliance_formed: string;
      alliance_broken: string;
      faction_formed: string;
      faction_dissolved: string;
      betrayal: string;
      major_battle: string;
      power_shift: string;
      minor_impact: string;
      major_impact: string;
      critical_impact: string;
    };
  };
  reports: {
      title: string;
      filter_all: string;
      filter_military: string;
      filter_economy: string;
      filter_research: string; 
      filter_archived: string; 
      details_loot: string;
      details_stolen: string;
      buildings_seized: string;
      infrastructure_lost: string;
      diamond_damaged: string;
      details_losses: string;
      details_enemies: string;
      empty_archive: string; 
      empty_inbox: string; 
      view_report: string; 
      combat_analysis: string; 
      integrity: string; 
      rounds: string; 
      damage_dealt: string; 
      unit_performance: string; 
      deployed: string; 
      lost: string; 
      survived: string; 
      wipeout: string; 
      friendly: string; 
      hostile: string; 
      unit_type: string; 
      enemy_suffix: string; 
      log_desertion: string;
      log_intel_acquired: string;
      intel_target: string;
      intel_strength: string;
      intel_composition: string;
      kill_analysis: string;
      targets_neutralized: string;
      fell_to: string;
      no_data: string;
      efficiency: string;
      analysis_kill_text: string;
      analysis_death_text: string;
      critical_bio: string;
      critical_mech: string;
      no_loot: string;
      no_losses: string;
      no_kills: string;
      no_casualties: string;
      hostile_force: string;
      enemy_target: string;
      you_label: string;
  };
  market: { 
      title: string;
      status: string;
      no_connection: string;
      offers: string;
      next_refresh: string;
      event_report: string;
      offer_buy: string;
      offer_sell: string;
      price: string;
      available: string;
      sold_out: string;
      liquidation_title: string;
      your_diamonds: string;
      rate_desc: string;
      exchange_btn: string;
      events: Record<string, { title: string, desc: string }>;
  };
  simulator: { 
      title: string;
      history_btn: string;
      history_title: string;
      history_empty: string;
      save_result: string;
      pwr_abbr: string;
      win: string;
      loss: string;
      draw: string;
      vs: string;
      battle_log: string;
      round: string;
      dmg_dealt: string;
      dmg_received: string;
      casualties: string;
      result_win: string;
      result_loss: string;
      total_rounds: string;
      attacker_power: string;
      defender_power: string;
      col_unit: string;
      col_deployed: string;
      col_survivors: string;
  };
  campaign: {
      title: string;
      level_prefix: string;
      status_locked: string;
      status_unlocked: string;
      status_completed: string;
      intel_report: string;
      mission_brief: string;
      rewards: string;
      enemy_forces: string;
      launch_assault: string;
      victory_title: string;
      defeat_title: string;
      victory_msg: string;
      defeat_msg: string;
      close: string;
      cooldown_msg: string;
      mission_in_progress: string;
      eta: string;
      levels: Record<string, { title: string, desc: string }>;
      difficulty: Record<string, string>;
  };
  offline: {
      title: string;
      welcome_back: string;
      time_away: string;
      report_status: string;
      production_summary: string;
      bank_interest: string;
      research_completed: string;
      missions_completed: string;
      claim: string;
  };
  features: {
      rankings: {
          title: string;
          current_rank: string;
          rank: string;
          commander: string;
          score: string;
          tier: string;
          trend: string;
          range_error: string;
          class_suffix: string;
          personality: string;
          types: Record<string, string>;
      };
      war: {
          losses_report: string;
          investment_lost: string;
          troop_casualties: string;
          tactical_status: string;
      you: string;
      amount: string;
          enemy: string;
          rate: string;
          wins: string;
          success: string;
          current_pool: string;
          pool_desc: string;
          est_payout: string;
          next_threat: string;
      };
  };
  buildings: Record<string, { name: string; description: string }>;
  units: Record<string, { name: string; stats: string }>;
  techs: Record<string, { name: string; description: string }>; 
  missions: {
    zone_risk_low: string;
    zone_risk_medium: string;
    zone_risk_high: string;
    zone_risk_extreme: string;
    patrol: {
      title: string;
      desc: string;
      select_units: string;
      duration: string;
      in_progress: string;
      complete: string;
      start_btn: string;
      log_loot: string;
      log_mercs: string;
      log_wipeout: string;
      log_battle_win: string;
      log_battle_loss: string;
      log_nothing: string;
      log_patrol_nothing: string;
      log_patrol_ambush: string;
      log_patrol_battle_win: string;
      log_patrol_battle_loss: string;
      log_patrol_contraband: string;
      intel_title: string;
      intel_desc: string;
      intel_risk: string;
      intel_reward: string;
      no_event_chance: string;
      contraband_chance: string;
      battle_chance: string;
      ambush_chance: string;
      mechanic_note: string;
      patrol_duration_label: string;
      zone_1: string;
      zone_2: string;
      zone_3: string;
      zone_4: string;
      est_capacity: string;
    };
  };
  tutorial: Record<string, string>; 
  errors: {
    insufficient_funds: string;
    req_building: string;
    req_tech: string;
    offline: string;
    storage_full: string;
    insufficient_units: string;
    invalid_mission: string;
    research_busy: string;
    campaign_cooldown: string;
    campaign_busy: string;
    market_limit: string; 
    market_stock: string; 
    queue_full: string;
    missing_diamond: string;
    protection_active: string;
    war_active_lock: string;
    campaign_slots_full: string;
    req_score: string;
  };
}
