
export enum ResourceType {
  MONEY = 'MONEY',
  OIL = 'OIL',
  AMMO = 'AMMO',
  GOLD = 'GOLD',
  DIAMOND = 'DIAMOND'
}

export enum BuildingType {
  // Economy
  HOUSE = 'HOUSE',
  FACTORY = 'FACTORY',
  SKYSCRAPER = 'SKYSCRAPER',
  BANK = 'BANK',
  MARKET = 'MARKET',
  DIAMOND_MINE = 'DIAMOND_MINE',
  
  // Resources
  OIL_RIG = 'OIL_RIG', 
  GOLD_MINE = 'GOLD_MINE',
  MUNITIONS_FACTORY = 'MUNITIONS_FACTORY',
  
  // Military / Research
  UNIVERSITY = 'UNIVERSITY',
  BARRACKS = 'BARRACKS', 
  TANK_FACTORY = 'TANK_FACTORY',
  SHIPYARD = 'SHIPYARD',
  AIRFIELD = 'AIRFIELD'
}

export enum UnitCategory {
  GROUND = 'GROUND',
  ARTILLERY = 'ARTILLERY',
  TANK = 'TANK',
  NAVAL = 'NAVAL',
  AIR = 'AIR'
}

export enum UnitType {
  CYBER_MARINE = 'CYBER_MARINE',
  HEAVY_COMMANDO = 'HEAVY_COMMANDO',
  SCOUT_TANK = 'SCOUT_TANK',
  TITAN_MBT = 'TITAN_MBT',
  WRAITH_GUNSHIP = 'WRAITH_GUNSHIP',
  ACE_FIGHTER = 'ACE_FIGHTER',
  AEGIS_DESTROYER = 'AEGIS_DESTROYER',
  PHANTOM_SUB = 'PHANTOM_SUB'
}

export enum TechCategory {
  MILITARY_GROUND = 'MILITARY_GROUND',
  MILITARY_MECH = 'MILITARY_MECH',
  MILITARY_NAVAL = 'MILITARY_NAVAL',
  MILITARY_AIR = 'MILITARY_AIR',
  LOGISTICS = 'LOGISTICS',
  PRODUCTIVE = 'PRODUCTIVE'
}

export enum TechType {
  // Productive
  EFFICIENT_WORKFLOWS = 'EFFICIENT_WORKFLOWS',
  DEEP_DRILLING = 'DEEP_DRILLING',
  GOLD_REFINING = 'GOLD_REFINING',
  MASS_PRODUCTION = 'MASS_PRODUCTION',
  
  // Logistics
  RESOURCE_MANAGEMENT = 'RESOURCE_MANAGEMENT',
  STRATEGIC_COMMAND = 'STRATEGIC_COMMAND',

  // --- MILITARY TREE ---
  BASIC_TRAINING = 'BASIC_TRAINING',
  ADV_INFANTRY_TACTICS = 'ADV_INFANTRY_TACTICS',
  PATROL_TRAINING = 'PATROL_TRAINING',
  BALLISTICS = 'BALLISTICS',
  EXPLOSIVE_CHEMISTRY = 'EXPLOSIVE_CHEMISTRY',
  COMBUSTION_ENGINE = 'COMBUSTION_ENGINE',
  HEAVY_PLATING = 'HEAVY_PLATING',
  NAVAL_ENGINEERING = 'NAVAL_ENGINEERING',
  SONAR_TECH = 'SONAR_TECH',
  STEALTH_HULL = 'STEALTH_HULL',
  AERODYNAMICS = 'AERODYNAMICS',
  JET_ENGINES = 'JET_ENGINES',
  PRECISION_BOMBING = 'PRECISION_BOMBING',

  // Unit Unlocks
  UNLOCK_CYBER_MARINE = 'UNLOCK_CYBER_MARINE',
  UNLOCK_HEAVY_COMMANDO = 'UNLOCK_HEAVY_COMMANDO',
  UNLOCK_SCOUT_TANK = 'UNLOCK_SCOUT_TANK',
  UNLOCK_TITAN_MBT = 'UNLOCK_TITAN_MBT',
  UNLOCK_WRAITH_GUNSHIP = 'UNLOCK_WRAITH_GUNSHIP',
  UNLOCK_ACE_FIGHTER = 'UNLOCK_ACE_FIGHTER',
  UNLOCK_AEGIS_DESTROYER = 'UNLOCK_AEGIS_DESTROYER',
  UNLOCK_PHANTOM_SUB = 'UNLOCK_PHANTOM_SUB'
}

export enum BotPersonality {
  WARLORD = 'WARLORD',
  TURTLE = 'TURTLE',
  TYCOON = 'TYCOON',
  ROGUE = 'ROGUE'
}
