CREATE TABLE IF NOT EXISTS public.player_resources (
  player_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  money DOUBLE PRECISION NOT NULL DEFAULT 5000,
  oil DOUBLE PRECISION NOT NULL DEFAULT 2500,
  ammo DOUBLE PRECISION NOT NULL DEFAULT 1500,
  gold DOUBLE PRECISION NOT NULL DEFAULT 500,
  diamond DOUBLE PRECISION NOT NULL DEFAULT 5,
  money_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  oil_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  ammo_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  gold_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  diamond_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  money_max DOUBLE PRECISION NOT NULL DEFAULT 999999999999999,
  oil_max DOUBLE PRECISION NOT NULL DEFAULT 999999999999999,
  ammo_max DOUBLE PRECISION NOT NULL DEFAULT 999999999999999,
  gold_max DOUBLE PRECISION NOT NULL DEFAULT 999999999999999,
  diamond_max DOUBLE PRECISION NOT NULL DEFAULT 10,
  bank_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  interest_rate DOUBLE PRECISION NOT NULL DEFAULT 0.15,
  next_rate_change BIGINT NOT NULL DEFAULT 0,
  last_tick_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.player_resources ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'player_resources'
      AND policyname = 'Users read own resources'
  ) THEN
    CREATE POLICY "Users read own resources" ON public.player_resources
      FOR SELECT USING (auth.uid() = player_id);
  END IF;
END
$$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.player_resources;
